name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run import tests
      run: |
        python test_imports.py
    
    - name: Run linting
      run: |
        ruff check chronos_mcp
    
    - name: Check formatting
      run: |
        black --check chronos_mcp tests
    
    # TODO: Add pytest when unit tests are written
    - name: Run tests
      run: |
        pytest